---
title: "Loading, Modifying, and Exploring the Job's Dataset"
author: "Grayson Ricketts"
date: "11/6/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev='png', fig.path='Figs/',
                      fig.width = 8.5, fig.height = 5,
                      echo = TRUE, warnings = FALSE)

library(ggplot2)
theme_set(theme_minimal())
```

# Load and Factor Data

## Load data
```{r}
lalonde <- read.table("job_training_observational_data.txt", header = TRUE)

# Removes the response variable so that the design is not biased by outcomes
lalonde <- within(lalonde, rm('RE78'))

# Removes redundant variable already represented by TREAT
lalonde <- within(lalonde, rm("TYPE"))
```

## Add 'OTHER' race to data
```{r}
lalonde$OTHER.RACE <- ifelse(lalonde$BLACK == 0 & lalonde$HISPANIC == 0, 1, 0)
```

# Explore and understand covariates

## Get frequencies of categorical variables to compare proportion of variables between treatment and control
```{r}
categorical <- c("MARR", "NODEGREE", "BLACK", "HISPANIC", "U74", "U75", "OTHER.RACE")
freq <- data.frame(row.names = c("factor", "freq", "treatment"))

num.treat <- nrow(lalonde[lalonde$TREAT == 1, ])
num.control <- nrow(lalonde) - num.treat

for (factor in categorical) {
  freq.treat <- sum(lalonde[lalonde[[factor]] & lalonde$TREAT == 1, c(factor)]) / num.treat
  freq.control <- sum(lalonde[lalonde[[factor]] & lalonde$TREAT == 0, c(factor)]) / num.control
  
  freq.new <- data.frame(factor=c(factor, factor), 
                        freq=c(freq.treat, freq.control),
                        treatment=c(TRUE, FALSE))
  freq <- rbind(freq, freq.new)
}
print(freq)
```

## Distribution of income in '74 and '75 for treatment and control groups (98th Quantile)

```{r}
lalonde$TREAT.CAT <- factor(lalonde$TREAT, labels=c("Control", "Treatment"))

ggplot(lalonde[lalonde$RE74 < quantile(lalonde$RE74, .98), ], aes(RE74, fill = factor(TREAT.CAT))) +
  geom_histogram(aes(y = ..density..), alpha = .5, position = "identity")

ggplot(lalonde[lalonde$RE74 < quantile(lalonde$RE75, .98), ], aes(RE75, fill = factor(TREAT.CAT))) +
  geom_histogram(aes(y = ..density..), alpha = .5, position = "identity")

ggplot(lalonde[lalonde$RE74 < quantile(lalonde$RE75, .98), ], aes(AGE, fill = factor(TREAT.CAT))) +
  geom_histogram(aes(y = ..density..), alpha = .5, position = "identity")

ggplot(lalonde[lalonde$RE74 < quantile(lalonde$RE75, .98), ], aes(EDUC, fill = factor(TREAT.CAT))) +
  geom_histogram(aes(y = ..density..), alpha = .5, position = "identity", binwidth = 1)
```

